import fs from 'node:fs';
import crypto from 'node:crypto';
import { createLedgerEntry, reserve, consume, revoke } from './rsta034-ledger.mjs';
const token=process.env.GITHUB_TOKEN; const owner='socksninja'; const repo='-'; const branch='main'; const path='rsta-ledger/rsta034-ledger.json';
if(!token) throw new Error('GITHUB_TOKEN_REQUIRED');
async function gh(method,url,body){const r=await fetch(url,{method,headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={raw:t}}return{status:r.status,ok:r.ok,json:j}}
async function getLedger(){const r=await gh('GET',`https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=${branch}`);if(r.status===404)return{sha:null,ledger:{schema:'RNCP-PERSISTENT-DELEGATION-LEDGER-v1',version:0,entries:[]}};if(!r.ok)throw Error(`GET_${r.status}`);return{sha:r.json.sha,ledger:JSON.parse(Buffer.from(r.json.content.replace(/\n/g,''),'base64').toString())}}
async function put(ledger,sha,label){const payload={message:`rsta034: ${label} [skip ci]`,content:Buffer.from(JSON.stringify(ledger,null,2)+'\n').toString('base64'),branch};if(sha)payload.sha=sha;return gh('PUT',`https://api.github.com/repos/${owner}/${repo}/contents/${path}`,payload)}
function accept(x){if(x.decision!=='ACCEPT')throw Error(x.code||'STATE_REJECT');return x.entry}
const prior=JSON.parse(fs.readFileSync('rsta033-execution-receipt.json','utf8')); if(prior.verdict!=='PASS')throw Error('RSTA033_NOT_PASS');
let {sha,ledger}=await getLedger(); const run=process.env.GITHUB_RUN_ID; const scope=prior.delegation||{}; const mk=id=>createLedgerEntry({delegationId:id,delegationHash:prior.chain.delegation_hash,subjectId:'SUBJECT-RSTA-033',executorId:'EXTERNAL-GITHUB-EXECUTOR',commitmentHash:prior.chain.commitment_hash,scope});
const A=mk(`RSTA-034-REVOKED-${run}`); ledger.entries.push(A); ledger.version++; let r=await put(ledger,sha,'create revoked entry'); if(!r.ok)throw Error(`WRITE_${r.status}`); sha=r.json.content.sha;
const AR=accept(reserve(A)); ledger.entries.at(-1)=AR; ledger.version++; const staleSha=sha; r=await put(ledger,sha,'reserve revoked entry'); if(!r.ok)throw Error(`WRITE_${r.status}`); sha=r.json.content.sha;
const AX=accept(revoke(AR)); ledger.entries.at(-1)=AX; ledger.version++; r=await put(ledger,sha,'persist revocation'); if(!r.ok)throw Error(`WRITE_${r.status}`); sha=r.json.content.sha;
const stalePayload={...ledger,version:ledger.version+1,entries:ledger.entries.map(e=>e.delegation_id===AX.delegation_id?{...e,state:'CONSUMED',version:e.version+1}:e)}; const stale=await put(stalePayload,staleSha,'stale writer'); if(stale.status!==409)throw Error(`STALE_WRITER_${stale.status}`);
let cur=await getLedger(); const persistedRevoked=cur.ledger.entries.find(e=>e.delegation_id===AX.delegation_id); if(persistedRevoked?.state!=='REVOKED')throw Error('REVOCATION_NOT_PERSISTED');
const B=mk(`RSTA-034-CONSUME-${run}`); ledger=cur.ledger; sha=cur.sha; ledger.entries.push(B); ledger.version++; r=await put(ledger,sha,'create consumable entry'); if(!r.ok)throw Error(`WRITE_${r.status}`); sha=r.json.content.sha;
const BR=accept(reserve(B)); ledger.entries.at(-1)=BR; ledger.version++; const replaySha=sha; r=await put(ledger,sha,'reserve consumable entry'); if(!r.ok)throw Error(`WRITE_${r.status}`); sha=r.json.content.sha;
const BC=accept(consume(BR)); ledger.entries.at(-1)=BC; ledger.version++; r=await put(ledger,sha,'persist consume'); if(!r.ok)throw Error(`WRITE_${r.status}`); sha=r.json.content.sha;
const replay=await put({...ledger,version:ledger.version+1},replaySha,'replay writer'); if(replay.status!==409)throw Error(`REPLAY_${replay.status}`);
cur=await getLedger(); const persistedConsumed=cur.ledger.entries.find(e=>e.delegation_id===BC.delegation_id); if(persistedConsumed?.state!=='CONSUMED')throw Error('CONSUME_NOT_PERSISTED');
const localRevoked=consume(AX); const localReserved=reserve(BR); if(localRevoked.decision!=='REJECT'||localReserved.decision!=='REJECT')throw Error('LOCAL_STATE_GUARD_FAILED');
const assertions={prior_rsta033_verified:true,real_external_persistent_ledger:true,reservation_persisted:true,revocation_persists_in_external_store:persistedRevoked.state==='REVOKED',stale_writer_conflict_denied:stale.status===409,revoked_before_execution_denied:localRevoked.decision==='REJECT',consume_persisted:persistedConsumed.state==='CONSUMED',consumed_replay_conflict_denied:replay.status===409,illegal_local_retransition_denied:localReserved.decision==='REJECT',ledger_reloaded_after_writes:true};
const receipt={schema:'RNCP-EXECUTION-RECEIPT-v1',rsta:'RSTA-034',execution:{provider:'github-actions',workflow:process.env.GITHUB_WORKFLOW,run_id:Number(run),head_commit:process.env.GITHUB_SHA},ledger:{repository:`${owner}/${repo}`,path,final_blob_sha:cur.sha,final_version:cur.ledger.version},observations:{stale_writer_http_status:stale.status,replay_writer_http_status:replay.status,revoked_state:persistedRevoked.state,consumed_state:persistedConsumed.state},assertions,verdict:Object.values(assertions).every(Boolean)?'PASS':'FAIL'};
receipt.content_address=crypto.createHash('sha256').update(JSON.stringify(receipt)).digest('hex'); fs.writeFileSync('rsta034-execution-receipt.json',JSON.stringify(receipt,null,2)); fs.writeFileSync('rsta034-final-verdict.json',JSON.stringify({rsta:'RSTA-034',status:receipt.verdict,protocol:'RNCP-PERSISTENT-DELEGATION-LEDGER-v1',assertions,claim_boundary:'Real GitHub Contents API persistence and blob-SHA optimistic concurrency conflict detection are proven; arbitrary distributed linearizability is not claimed.'},null,2)); console.log(JSON.stringify(receipt,null,2));