'use client';

import { useState } from 'react';

const opportunities = [
  { score: 96, type: 'EARLY PROJECT SIGNAL', title: 'Logistics Center — Milan, Italy', value: '€28M est. project value', fit: 'Façade / HVAC / building systems', evidence: ['Planning approval updated', 'General contractor identified', 'Specification-stage hiring detected'], action: 'Approach the design / specification team before tender.' },
  { score: 91, type: 'EMERGING PROCUREMENT', title: 'Food Processing Expansion — Pune, India', value: 'New production line', fit: 'Processing / packaging equipment', evidence: ['Plant expansion announcement', 'Engineering roles opened', 'Utilities upgrade activity'], action: 'Validate line requirements and identify procurement ownership.' },
  { score: 87, type: 'COMPETITIVE WINDOW', title: 'Industrial Campus — Warsaw, Poland', value: 'Multi-building program', fit: 'Industrial automation / MEP', evidence: ['Phase-two project notice', 'Supplier registration activity', 'New project management hiring'], action: 'Map incumbent suppliers and enter before RFQ.' }
];

export default function OrionPage() {
  const [selected, setSelected] = useState(opportunities[0]);
  const [email, setEmail] = useState('');
  const [sent, setSent] = useState(false);

  return (
    <main className="site">
      <style dangerouslySetInnerHTML={{ __html: `
        :root{--bg:#080b0d;--panel:#0e1317;--line:#252d33;--text:#f4f6f7;--muted:#8d99a2;--soft:#b9c2c9;--accent:#e9f1ed}
        *{box-sizing:border-box}html,body{margin:0;background:radial-gradient(circle at 15% 5%,#141b20 0,#0a0d0f 35%,#080b0d 72%);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif}
        body{min-height:100vh}.site{max-width:1240px;margin:0 auto;padding:22px 24px 64px}.nav{display:flex;justify-content:space-between;align-items:center;padding:8px 0 34px}.brand{letter-spacing:.22em;font-weight:800}.nav span{color:var(--muted);font-size:12px;letter-spacing:.12em}.hero{display:grid;grid-template-columns:1.05fr .95fr;gap:40px;align-items:center;padding:46px 0 54px}.eyebrow{color:var(--muted);font-size:12px;letter-spacing:.2em;text-transform:uppercase}.hero h1{font-size:clamp(52px,8vw,92px);line-height:.91;letter-spacing:-.055em;margin:16px 0 22px}.hero p{font-size:20px;line-height:1.55;max-width:700px;color:var(--soft);margin:0}.tagline{margin-top:28px;font-size:14px;color:#d6dfda;letter-spacing:.08em}.orb{height:430px;border:1px solid var(--line);border-radius:28px;position:relative;overflow:hidden;background:linear-gradient(145deg,rgba(255,255,255,.03),rgba(255,255,255,.005));box-shadow:inset 0 0 90px rgba(200,220,210,.06)}.orb:before,.orb:after{content:"";position:absolute;border:1px solid rgba(233,241,237,.15);border-radius:50%;left:50%;top:50%;transform:translate(-50%,-50%)}.orb:before{width:360px;height:360px}.orb:after{width:210px;height:210px}.core{position:absolute;left:50%;top:50%;width:14px;height:14px;border-radius:50%;transform:translate(-50%,-50%);background:#eff7f2;box-shadow:0 0 34px rgba(239,247,242,.95)}.ray{position:absolute;left:50%;top:50%;width:82%;height:1px;background:linear-gradient(90deg,transparent,rgba(233,241,237,.22),transparent)}.r1{transform:translate(-50%,-50%) rotate(18deg)}.r2{transform:translate(-50%,-50%) rotate(-31deg)}.r3{transform:translate(-50%,-50%) rotate(64deg)}
        .section{background:rgba(14,19,23,.88);border:1px solid var(--line);border-radius:20px;padding:22px}.section h2{font-size:18px;margin:0 0 6px}.sub{color:var(--muted);font-size:13px;margin-bottom:18px}.controls{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:10px}.control{background:#0a0e11;border:1px solid #2a333a;border-radius:12px;padding:12px 13px;color:#eef1f3;font:inherit}.btn{background:var(--accent);color:#0a0d0f;border:0;border-radius:12px;padding:12px 18px;font-weight:800;cursor:pointer}.opps{display:grid;gap:12px;margin-top:16px}.opp{border:1px solid #222b31;background:linear-gradient(180deg,#10161a,#0a0e11);border-radius:16px;padding:16px;cursor:pointer}.opp:hover{border-color:#536069}.opp-top{display:flex;justify-content:space-between;gap:16px}.type{font-size:10px;letter-spacing:.15em;color:#94a29b}.opp h3{font-size:17px;margin:7px 0}.opp p{margin:0;color:#aeb8bf;font-size:13px;line-height:1.5}.score{min-width:52px;background:#171f24;border-radius:10px;padding:8px 10px;text-align:center;font-weight:800}.meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:11px}.pill{font-size:11px;color:#9daab2;border:1px solid #28323a;border-radius:999px;padding:5px 8px}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:18px;margin-top:18px}.chain{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:16px}.step{border:1px solid #242e35;background:#0b1013;border-radius:14px;padding:14px}.step b{display:block;font-size:12px;margin-bottom:6px}.step span{font-size:11px;line-height:1.45;color:#88959d}.details{margin-top:16px;border:1px dashed #2b353c;border-radius:15px;padding:15px;background:#0a0e11}.details strong{display:block;margin-bottom:8px}.details div{font-size:12px;color:#aab4bb;line-height:1.6}.cta{margin-top:20px;display:flex;gap:10px}.cta input{flex:1;min-width:0}.success{margin-top:10px;font-size:12px;color:#bfe0ca}.footer{display:flex;justify-content:space-between;color:#5f6b73;font-size:11px;margin-top:28px}
        @media(max-width:900px){.hero,.grid{grid-template-columns:1fr}.orb{height:300px}.controls{grid-template-columns:1fr 1fr}.controls .btn{grid-column:1/-1}.chain{grid-template-columns:1fr}.footer{flex-direction:column;gap:8px}}
      `}} />
      <div className="nav"><div className="brand">ORION</div><span>PROJECT INTELLIGENCE</span></div>
      <section className="hero"><div><div className="eyebrow">Before the obvious</div><h1>See the projects<br/>worth acting on.</h1><p>ORION watches the open web for projects, procurement activity and market changes, then turns scattered signals into a short list of opportunities your sales team can actually pursue.</p><div className="tagline">Observe → verify → prioritize → act</div></div><div className="orb"><div className="ray r1"/><div className="ray r2"/><div className="ray r3"/><div className="core"/></div></section>
      <section className="section"><h2>Today's opportunity radar</h2><div className="sub">Example intelligence for building-product manufacturers, industrial suppliers and distributors.</div><div className="controls"><input className="control" defaultValue="Building products / industrial systems" aria-label="Product category"/><select className="control"><option>Europe</option><option>India</option><option>Middle East</option><option>Global</option></select><select className="control"><option>Early project signal</option><option>Emerging procurement</option><option>Competitive window</option></select><button className="btn">Refresh radar</button></div><div className="opps">{opportunities.map((o,i)=><article className="opp" key={o.title} onClick={()=>setSelected(o)}><div className="opp-top"><div><div className="type">{o.type}</div><h3>{o.title}</h3></div><div className="score">{o.score}</div></div><p>{o.value} · Fit: {o.fit}</p><div className="meta"><span className="pill">evidence-backed</span><span className="pill">priority scored</span><span className="pill">actionable</span></div></article>)}</div></section>
      <div className="grid"><section className="section"><h2>Why this opportunity?</h2><div className="sub">No “AI says so.” Every recommendation starts with evidence.</div><div className="details"><strong>{selected.title}</strong><div><b>Evidence</b><br/>{selected.evidence.map((e,i)=><span key={i}>• {e}<br/></span>)}</div><div style={{marginTop:10}}><b>Recommended action</b><br/>{selected.action}</div></div><div className="chain"><div className="step"><b>01 Observe</b><span>Projects, permits, hiring, announcements, tenders, supplier signals.</span></div><div className="step"><b>02 Verify</b><span>Cross-check sources and separate facts from inference.</span></div><div className="step"><b>03 Prioritize</b><span>Rank the opportunities most worth sales attention now.</span></div></div></section><aside className="section"><h2>Get the weekly radar</h2><div className="sub">A short list of the projects your team should know about.</div><div style={{fontSize:13,color:'#aeb8bf',lineHeight:1.55}}>Start with a human-reviewed pilot. We configure the watchlist around your products, territories and project size.</div><div className="cta"><input className="control" value={email} onChange={e=>setEmail(e.target.value)} placeholder="work email" type="email"/><button className="btn" onClick={()=>setSent(true)}>Request sample</button></div>{sent&&<div className="success">Request captured for the prototype. We’ll use this only as a demo interaction.</div>}<div className="details"><strong>Built for action, not dashboards.</strong><div>Opportunity → evidence → contact path → next move → outcome.</div></div></aside></div>
      <div className="footer"><span>ORION / prototype</span><span>Intelligence before the obvious.</span></div>
    </main>
  );
}
